# Generated by Django 3.1.4 on 2020-12-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20201216_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewComment',
        ),
    ]
